### ISSUE TITLE
Python3-gi dependency issue

### ISSUE THREAD

**Issue by Artiume** [Artiume/docker-mopidy#1]
```
ERROR: A GObject based library was not found.
Mopidy requires GStreamer to work. GStreamer is a C library with a
number of dependencies itself, and cannot be installed with the regular
Python tools like pip.
Please see http://docs.mopidy.com/en/latest/installation/ for
instructions on how to install the required dependencies.
Traceback (most recent call last):
  File "/usr/bin/mopidy", line 11, in <module>
    load_entry_point('Mopidy==3.0.1', 'console_scripts', 'mopidy')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 480, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2693, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2324, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2330, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3/dist-packages/mopidy/__main__.py", line 7, in <module>
    from mopidy import commands
  File "/usr/lib/python3/dist-packages/mopidy/commands.py", line 14, in <module>
    from mopidy.audio import Audio
  File "/usr/lib/python3/dist-packages/mopidy/audio/__init__.py", line 2, in <module>
    from .actor import Audio
  File "/usr/lib/python3/dist-packages/mopidy/audio/actor.py", line 8, in <module>
    from mopidy.audio import tags as tags_lib
  File "/usr/lib/python3/dist-packages/mopidy/audio/tags.py", line 7, in <module>
    from mopidy.internal.gi import GLib, Gst
  File "/usr/lib/python3/dist-packages/mopidy/internal/gi.py", line 5, in <module>
    import gi
  File "/usr/lib/python3/dist-packages/gi/__init__.py", line 42, in <module>
    from . import _gi
ImportError: cannot import name '_gi' from 'gi' (/usr/lib/python3/dist-packages/gi/__init__.py)
```

https://askubuntu.com/questions/1201556/python3-7-with-libraries-ubuntu-18-04

https://www.reddit.com/r/Python/comments/dm4col/python3gi_not_working_complains_about_not_being/

**Comment by Artiume** [comment]
https://askubuntu.com/questions/1184950/during-setup-of-stable-docker-engine-repository-in-ubuntu-18-04-02-server-editio

**Comment by Artiume** [comment]
https://askubuntu.com/questions/80448/what-would-cause-the-gi-module-to-be-missing-from-python
